name: Cypress Integration
on:
  workflow_dispatch:
    inputs:
      client:
        description: 'Select a client'
        required: true
        type: choice
        options:
          - asurioncompletemyhome
          - homeplus
      additional-clients:
        description: 'Do we need additional client'
        type: boolean
        default: false
      clients:
        description: 'Mention additional clients here'
        type: string
        default: "['asurionmyhome','homeplus']"
jobs:
  read_inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "additional-clients: ${{ github.event.inputs.additional-clients }}" 
          echo "clients: ${{ github.event.inputs.clients }}"
          echo "client: ${{ github.event.inputs.client }}"
  
  multi_client_cypress:
    needs: [read_inputs]
    if: ${{ github.event.inputs.additional-clients == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        clients: ${{ fromJSON(github.event.inputs.clients) }}
    steps:
      - name: Multi clients cypress
        run: echo "running job with ${{ matrix.clients }} ${{ matrix.containers }}"
  
  single_client_cypress:
    needs: [read_inputs]
    if: ${{ github.event.inputs.additional-clients == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: running
        run: echo "running job with ${{ github.event.inputs.client }}"

  
